server:
  port: 8000

spring:
  datasource:
    url: jdbc:oracle:thin:@test.amazonaws.com:1521:ORCL     
    driver-class-name: oracle.jdbc.OracleDriver
    username: test
    password: 1111

# mybatis-config
mybatis:
  config-location: classpath:/mybatis/cfg/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  
# 로그 레벨
logging:
  level:
    '[org.springframework]': INFO
    '[com.potato.mono]': DEBUG
